### ISSUE TITLE
Needs LICENSE.txt file

### ISSUE THREAD

**Issue by paul-hammant** [lorenbrichter/ragmask#12]

**Comment by lorenbrichter** [comment]
https://github.com/lorenbrichter/ragmask/commit/10cf245e9aadf0eb44b01f29c63db46e9d19a415

**Comment by lorenbrichter** [comment]
Switch to: https://opencovidpledge.org

**Comment by Its-Gardner** [comment]
Tara is reviewing open covid pledge as well at 2 CC license types?

**Comment by lorenbrichter** [comment]
Consensus is to keep CC.
