### ISSUE TITLE
Translator Email / Guide

### ISSUE THREAD

**Issue by Its-Gardner** [lorenbrichter/ragmask#14]
Welcome translators!

Thank you for your generosity. Your work will help protect people, communities, and nations. 

Your response to this note with the following information will be most helpful:
	1) Name:
        2) Country of Residence:
        3) Language (and dialect if applicable): 
        4) Your preferred choice from the three options below:
        5) May we contact you for future translations?
————————————————————————————————
You can provide your translations in three ways. Our preference is in descending order, but please choose whatever is most comfortable to you. 

Option 1 - Github
If you are familiar with Github, please submit a pull request with a translated version of the following file:

https://github.com/lorenbrichter/ragmask/tree/master/pages/ragmask_2.3.pages

You can name it with the two-letter code of the translated language, e.g. ragmask_2.3_xx.pages (where 'xx' is the two letter code).

The PDF file will be created from the Pages file, and compressed (https://tools.pdf24.org/en/compress-pdf#s=1585782995305 is a great tool, all of the PDF files are currently compressed with that, at 90% quality).

If you'd also like to add the compressed PDF files, and edit the index.html file as part of the pull request with the appropriate links, that would be great, but if you're not comfortable doing that it's easy for us to do on our end.

Option 2 - Pages App (mac) Direct Edit
If you have the Pages App, please directly edit the Pages document and save as a new pages file. The completed files can be sent to translations@ragmask.com.

https://github.com/lorenbrichter/ragmask/blob/master/pages/ragmask_2.3.pages

Option 3 - Text Doc
If you do not use GitHub or have the Pages app, please translate the following into separate text files, and email to translations@ragmask.com.

https://ragmask.com/ragmask.pdf

We and the world thank you!
-Team ragmask

**Comment by lorenbrichter** [comment]
Cool. The "materials" and "pro" pages are still all over the place, might want to refine those before asking for translations?

**Comment by Its-Gardner** [comment]
_Sure, whenever you think it makes sense. Revised below, please make any needed edits (see "???"s in option 1), then I'll get this out...._


Welcome translators!

Thank you for your generosity. Your work will help protect people, communities, and nations.

Your initial response to this email with the following information will be most helpful (send to translations@ragmask.com):
1) Name:
2) Country of Residence:
3) Language (and dialect if applicable):
4) Your preferred choice from the three options below:
5) May we contact you for future translations?

————————————————————————————————

You can provide your translations in three ways. Our preference is in descending order, but please choose whatever is most comfortable to you.

Option 1 - Github
If you are familiar with Github, please create and upload a translated version of https://github.com/lorenbrichter/ragmask/tree/master/pages/ragmask_2.3.pages
_**???proper github terminology???specify file naming conventions???**_

Option 2 - Pages App (mac) Direct Edit
If you have the Pages App, please download then directly edit the design document found at https://github.com/lorenbrichter/ragmask/blob/master/pages/ragmask_2.3.pages. Save as a new pages file and send to translations@ragmask.com.

Option 3 - Text Doc
If you do not use GitHub or have the Pages app, please translate https://ragmask.com/ragmask.pdf into a text document and email to translations@ragmask.com.


————————————————————————————————
We and the world thank you!
-Team ragmask

**Comment by Its-Gardner** [comment]
Still considering bringing someone on to handle translations? Jason Lang or Rocky Moon?

**Comment by lorenbrichter** [comment]
Was going to link to this Issue, but probably better to add to Wiki.

Added Wiki page, and now link to it directly from ragmask.com

https://github.com/lorenbrichter/ragmask/wiki/Translator-Guide
