### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by lorenbrichter** [lorenbrichter/ragmask#4]
1. N'imprimez que cette page.
Vous n'avez pas besoin des autres pages, Èconomisez votre papier.

2. VÈrifiez l'Èchelle.
Assurez-vous qu'elle est imprimÈe ‡ la bonne taille. Une vraie rËgle devrait correspondre ‡ celle ci-dessous.

3. DÈcoupez les matÈriaux.
28x28cm de tissu, 1 par masque
2,5x40cm de tissu pour les attaches, 4 par masque
26x13cm de filtre (facultatif*), 1 par masque
10cm de fil mÈtallique, 1 par masque, (du fil de cuivre de diamËtre 1,5mm fonctionne bien)

*L'efficacitÈ des diffÈrents matÈriaux pour le filtre sera communiquÈe prochainement.
Voir ragmask.com/materials pour les derniËres informations.
Porter un masque sans filtre (juste en tissu), peut Ítre plus efficace que ne pas porter de masque du tout.

4. Pliez le tissu par-dessus le filtre.

5. Cousez sur les trois cÙtÈs.
Laissez une marge d'environ 5mm, rapide>joli.

6. Pliez

7. Marquez.

Utilisez le patron de la page 1.

8. Cousez.
Commencez ici ->

9. Coupez.

10. Retournez.

11. Marquez l'emplacement des attaches.

12. Cousez les attaches sur l'extÈrieur du masque.
Voir la derniËre page pour une faÁon encore plus rapide d'installer les attaches.

13. InsÈrez le fil mÈtallique au centre au-dessus du nez.

14. Mettez le fil en forme selon le contour du nez.

Portez.

Conseils d'utilisation et d'entretien ‡ venir...

Astuce : Attaches Rapides
Plus d'Astuces sur ragmask.com/pro

1. Imprimez une deuxiËme copie de la page 1, dÈcoupez-la selon le guide. AprËs avoir effectuÈ le premier pli, marquez le centre des attaches.

2. Fixez les attaches pendant la premiËre couture (surpiquez par-dessus les attaches pour renforcer.)

3. Pliez en deux (attaches ‡ l'intÈrieur du pli), marquez, cousez et dÈcoupez comme prÈcÈdemment.

**Comment by tristanbo** [comment]
Just did a FR pages + pdf french version, i'm still in the process of committing it properly (last commit was 13 years ago).   Attaching file here just in case.

[ragmask_2.2_fr.pdf](https://github.com/lorenbrichter/ragmask/files/4437991/ragmask_2.2_fr.pdf)

**Comment by tristanbo** [comment]
> Just did a FR pages + pdf french version, i'm still in the process of committing it properly (last commit was 13 years ago). Attaching file here just in case.
> 
> [ragmask_2.2_fr.pdf](https://github.com/lorenbrichter/ragmask/files/4437991/ragmask_2.2_fr.pdf)

I did a pull request of the whole thing.

**Comment by lorenbrichter** [comment]
Merged, should be live in a minute! Thanks again!
