### ISSUE TITLE
v2.3 design doc tweaks

### ISSUE THREAD

**Issue by lorenbrichter** [lorenbrichter/ragmask#7]
-Design doc callouts to reference more detailed info on website

-Scaling template print size for better fit? (mention that base material cut size would also need to be adjusted)

-Prototype evaluation
	Wash durability/fraying
	Fabric thickness/hole size/potential leakage @ front seam

-Materials choices
	Evaluating fabrics (light test, breathability)
	Nose wire materials

-Tips, things to look out for, etc?
	Perimeter Tape (silicone, other?) - seal, prevent fraying, comfort
	Proper use and care/cleaning

**Comment by lorenbrichter** [comment]
**Use anything.** Old bedsheets, pillowcases, dish towels, napkins. Literal rags. No need to go out any buy anything new, that would miss the point. Flannel is super cozy. High thread count stuff actually has pretty decent filtration ability even without a "real" filter layer.

I definitely get what you are going for with the casualness of your wording, but not certain it is best to say “**anything**” since certain fabrics are near 0% filtration. What about “**Use any tightly woven cotton fabric**”? Might not hurt to include mention of light test to check fabric gaps?

“Hold it up to a bright light,” said Dr. Scott Segal, chairman of anesthesiology at Wake Forest Baptist Health who recently studied homemade masks. “If light passes really easily through the fibers and you can almost see the fibers, it’s not a good fabric. If it’s a denser weave of thicker material and light doesn’t pass through it as much, that’s the material you want to use.”

**Comment by lorenbrichter** [comment]
Page 2

Many people leave the filter layer out! Cloth alone can be effective. For more information on filter layers (or lack thereof), plus lots of different **component options** visit ragmask.com/materials

Page 7
Adjust the nose wire to give the mask a comfortable, tight fit. Tie the upper straps behind your head above the ears, and the lower straps behind your head below the ears. **If the strap material has some stretch, once tied you can slide the strap higher to tighten the fit.**  The less you need to fiddle with the mask the better (hands spread disease), so take the time to make any adjustments when you first put it on. 


**Use**

**Minimizing contact with the inside and outside fabric of the mask will reduce chances of contamination. Using only the straps to put on and take off your mask will minimize this contact. Tying a bow or slipknot will allow for easiest removal.** 

**Cleaning**

**All masks should be thoroughly cleaned after each use.**

**Comment by lorenbrichter** [comment]
[ragmask_2.3_draft1.pdf](https://github.com/lorenbrichter/ragmask/files/4447587/ragmask_2.3_draft1.pdf)

**Comment by lorenbrichter** [comment]
<img width="570" alt="Screen Shot 2020-04-07 at 9 09 29 PM" src="https://user-images.githubusercontent.com/40109/78733677-18c39880-7914-11ea-8a51-376a729f6e63.png">
<img width="572" alt="Screen Shot 2020-04-07 at 9 09 35 PM" src="https://user-images.githubusercontent.com/40109/78733683-1a8d5c00-7914-11ea-92cb-1e32c598ecf0.png">

**Comment by lorenbrichter** [comment]
[ragmask_2.3_draft2.pdf](https://github.com/lorenbrichter/ragmask/files/4447689/ragmask_2.3_draft2.pdf)

**Comment by Its-Gardner** [comment]
Just so we don't have a 404 from the design doc for Sizing Tips.

Feel free to reword... these are rough but hopefully reasonable values for now? I can test some scaling tomorrow.

Rescale template printing size and the corresponding cut fabric size to adjust your mask's fit.
       Kids - 70-85%
       Small - 85-95% print size
       Medium - 95%-105% print size
       Large - 105%-115%
       XL - 115%+

**Comment by lorenbrichter** [comment]
2.3b2 is up, will keep this open for any minor tweaks left (removed reference to "ribbon" since it's might be hard to tie those, but it still might be good as a material choice for the "loop" version).
